### ISSUE TITLE
NODEPAY script not working

### ISSUE THREAD

**Issue by cryptoknightsz** [im-hanzou/ProXer#3]
NODEPAY SCRIPT ISN'T WORKING

**Comment by im-hanzou** [comment]
I already update the script to v2. Please use ``runv2.py``, but now is only single account feature and multi accounts feature is coming soon! 
Please check: https://github.com/im-hanzou/nodepay-automate

**Comment by cryptoknightsz** [comment]
Let me check

**Comment by im-hanzou** [comment]
okay

**Comment by cryptoknightsz** [comment]
![image](https://github.com/user-attachments/assets/2cd8357d-49d1-492c-b312-66db192aa0b0)
IT's not working

**Comment by im-hanzou** [comment]
> ![image](https://private-user-images.githubusercontent.com/67500412/391706720-2cd8357d-49d1-492c-b312-66db192aa0b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNzU4MjYsIm5iZiI6MTczMzE3NTUyNiwicGF0aCI6Ii82NzUwMDQxMi8zOTE3MDY3MjAtMmNkODM1N2QtNDlkMS00OTJjLWIzMTItNjZkYjE5MmFhMGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDIxMzg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNDBlNTE0MDdhNWY4Y2MwMmJiZGYxOGY1NTdkY2VhYjg1ZDA5MWRjY2MxYjFiZTQ4ZGU2NDQ4N2JkOTVjNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y2FZiLEt2v8LQGkcve-U7S4XGARTyElp-_3icf0GJKE) IT's not working

your token is expired, please get new token
and update the bot again, i fix some problem and add new features

**Comment by cryptoknightsz** [comment]
![image](https://github.com/user-attachments/assets/9dec020f-25ba-4801-a7d1-5c4dc0c7c680)
Another issue

**Comment by im-hanzou** [comment]
> ![image](https://private-user-images.githubusercontent.com/67500412/391830322-9dec020f-25ba-4801-a7d1-5c4dc0c7c680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTY0MDksIm5iZiI6MTczMzIxNjEwOSwicGF0aCI6Ii82NzUwMDQxMi8zOTE4MzAzMjItOWRlYzAyMGYtMjViYS00ODAxLWE3ZDEtNWM0ZGMwYzdjNjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA4NTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3Y2RjYzhlM2ZjMzhiYzgxNjIwM2E5MDEzODEzNWRhZjBkZTkxYzhhZDY5MGU1NWIzMTY0ZDI0ZWFiMTIxODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m7MtEfvIU_-cTESGd9YkSZCZ9itMx0mWvI7sfcwPQPk) Another issue

are you using windows? please use linux or install wsl. currently nodepay bot is work for linux only

**Comment by XNFTHUNETRZ** [comment]
Ah! Wen it'll be up again for windows with multi bypass version

**Comment by im-hanzou** [comment]
> Ah! Wen it'll be up again for windows with multi bypass version

Currently you can use WSL for windows, please install WSL first
check the readme: https://github.com/im-hanzou/nodepay-automate/blob/main/README.md

**Comment by im-hanzou** [comment]
Nodepay bot now work use windows and another operating system, but you need requirements before getting the token, please check readme: https://github.com/im-hanzou/nodepay-automate/blob/main/README.md#setup-tutorial

**Comment by XNFTHUNETRZ** [comment]
Thanks, let me test

**Comment by im-hanzou** [comment]
Okay, please download latest repository. I update some mechanism

**Comment by cryptoknightsz** [comment]
![image](https://github.com/user-attachments/assets/7b133564-0e59-4fff-ae04-13ad3befe29a)

**Comment by im-hanzou** [comment]
> ![image](https://private-user-images.githubusercontent.com/67500412/392035654-7b133564-0e59-4fff-ae04-13ad3befe29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNDIxMTgsIm5iZiI6MTczMzI0MTgxOCwicGF0aCI6Ii82NzUwMDQxMi8zOTIwMzU2NTQtN2IxMzM1NjQtMGU1OS00ZmZmLWFlMDQtMTNhZDNiZWZlMjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDE2MDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MDdmNzU0ODQxMzZmNzBhODlkNzk4Yjc5MjM0ZDBhMzRmODI3OWM2MzBiNmNiZmE4YThmMTRmMGZkZDdlMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KXHmwyVP0I3V_7QVYC1YVOF9zL4pwvEIKZD-UijuHiI)

are you using wsl/linux?

**Comment by XNFTHUNETRZ** [comment]
Wsl

**Comment by XNFTHUNETRZ** [comment]
I tried it in WSL (windows), without WSL (windows), changed 3 proxy provided (residential proxy, not cheap ones), changed token as they might have expired 
Nothing worked till now

**Comment by im-hanzou** [comment]
Script is updated, you can try ``git pull`` or re-download/re-git the script
make sure you have connected extension before getting the token at same browser
i use WSL and still work properly till now, im UTC+7

![image](https://github.com/user-attachments/assets/78517978-72cf-4921-ba2f-443f16bdc358)
